### ISSUE TITLE
Encrypt / decrypt API doesn't actually encrypt any message

### ISSUE THREAD

**Issue by drewstone** [guruvamsi-policharla/silent-threshold-encryption#2]
# Overview
The functions for `encrypt` and `agg_dec` don't actually deal with any message. They return the symmetric key or entropy used to actually do encryption/decryption afaik from our last discussion.

**Comment by guruvamsi-policharla** [comment]
The ciphertext struct contains an `enc_key` member: https://github.com/guruvamsi-policharla/silent-threshold-encryption/blob/ca2a816469b113ceeef058548675c3711b400422/src/encryption.rs#L16

This is to be used for key encapsulation. You could for instance do Hash-Based key derivation as `H(enc_key, "context")` and use this to encrypt the message via your favorite mode of AES
